import { NextRequest } from 'next/server';
import { abort, json, route } from '@/lib/http';
import {
  commitUniqueMarkdown,
  getGitHubConfig,
  GitHubCommitError,
  GitHubConfigError,
  localStamp,
  slugifyName,
} from '@/lib/github';

export const dynamic = 'force-dynamic';

// Repo-relative folder the task notes are committed under.
const TASK_TRACKER_REPO_DIR = 'Governance_Files/task_tracker';

// Raw employee keys are stored as "First_Last"; show a readable display name.
function employeeDisplayName(raw: string): string {
  return String(raw || '').replace(/_+/g, ' ').trim() || 'Unknown';
}

export const POST = route(async (req: NextRequest) => {
  const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;
  const company = String(body.company || '').trim();
  const employeeRaw = String(body.employee || '').trim();
  const markdown = String(body.markdown || '').trim();
  const createdBy = String(body.created_by || '').trim() || 'Unknown';

  if (!company) {
    abort(400, 'company required');
  }
  // Server-side validation mirrors the client gating (both fields required).
  if (!employeeRaw) {
    abort(400, 'Please select an employee.');
  }
  if (!markdown) {
    abort(400, 'Please enter a task description.');
  }

  // GitHub is the store — resolve credentials before doing any work.
  let cfg;
  try {
    cfg = getGitHubConfig();
  } catch (err) {
    if (err instanceof GitHubConfigError) {
      console.error('[task_tracker] GitHub not configured:', err.message);
      abort(500, err.message);
    }
    throw err;
  }

  const employeeName = employeeDisplayName(employeeRaw);
  const stamp = localStamp();
  const slug = slugifyName(employeeName);

  const content = [
    '# Task Tracker',
    '',
    '## Employee',
    employeeName,
    '',
    '## Created Date',
    stamp.dateDisplay,
    '',
    '## Created Time',
    stamp.timeDisplay,
    '',
    '## Created At',
    stamp.createdAt,
    '',
    '## Created By',
    createdBy,
    '',
    '## Task Description',
    '',
    markdown,
    '',
    '---',
    '',
    'Generated by Governance Workbench',
    '',
  ].join('\n');

  const baseName = `${stamp.datePart}_${stamp.timePart}_${slug}_task`;
  try {
    const saved = await commitUniqueMarkdown(
      cfg,
      TASK_TRACKER_REPO_DIR,
      baseName,
      content,
      (filename) => `Task Tracker: add task for ${employeeName} (${filename})`,
    );
    return json({
      ok: true,
      company,
      employee: employeeRaw,
      employee_name: employeeName,
      filename: saved.filename,
      repo_path: saved.repoPath,
      branch: cfg.branch,
      commit: saved.data?.commit?.sha || null,
      html_url: saved.data?.content?.html_url || null,
    });
  } catch (err) {
    if (err instanceof GitHubCommitError) {
      abort(err.status === 409 ? 409 : 502, `Could not save task to GitHub: ${err.message}`);
    }
    throw err;
  }
});
