import fs from 'fs';
import path from 'path';
import { NextRequest } from 'next/server';
import { abort, json, route } from '@/lib/http';
import { task_tracker_dir } from '@/lib/helpers';

export const dynamic = 'force-dynamic';

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

// Lowercase, spaces -> underscores, drop special characters. Used for the
// employee-name portion of the filename (e.g. "Pooja Wable" -> "pooja_wable").
function slugifyEmployee(name: string): string {
  const slug = String(name || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s_-]+/g, '') // remove special characters
    .replace(/[\s-]+/g, '_') // spaces / hyphens -> underscore
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  return slug || 'employee';
}

// Raw employee keys are stored as "First_Last"; show a readable display name.
function employeeDisplayName(raw: string): string {
  return String(raw || '').replace(/_+/g, ' ').trim() || 'Unknown';
}

export const POST = route(async (req: NextRequest) => {
  const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;
  const company = String(body.company || '').trim();
  const employeeRaw = String(body.employee || '').trim();
  const markdown = String(body.markdown || '').trim();
  const createdBy = String(body.created_by || '').trim() || 'Unknown';

  if (!company) {
    abort(400, 'company required');
  }
  // Server-side validation mirrors the client gating (both fields required).
  if (!employeeRaw) {
    abort(400, 'Please select an employee.');
  }
  if (!markdown) {
    abort(400, 'Please enter a task description.');
  }

  const employeeName = employeeDisplayName(employeeRaw);
  const now = new Date();
  const datePart = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  const timePart = `${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;

  let hour12 = now.getHours() % 12;
  if (hour12 === 0) hour12 = 12;
  const timeDisplay = `${hour12}:${pad(now.getMinutes())} ${now.getHours() >= 12 ? 'PM' : 'AM'}`;

  const slug = slugifyEmployee(employeeName);
  const dir = task_tracker_dir(company);

  // Guarantee a unique filename even if two tasks land in the same second.
  const base = `${datePart}_${timePart}_${slug}_task`;
  let filename = `${base}.md`;
  let counter = 2;
  while (fs.existsSync(path.join(dir, filename))) {
    filename = `${base}_${counter}.md`;
    counter += 1;
  }

  const content = [
    '# Task Tracker',
    '',
    '## Employee',
    employeeName,
    '',
    '## Created Date',
    datePart,
    '',
    '## Created Time',
    timeDisplay,
    '',
    '## Created By',
    createdBy,
    '',
    '## Task Description',
    '',
    markdown,
    '',
    '---',
    '',
    'Generated by Governance Workbench',
    '',
  ].join('\n');

  const outputPath = path.join(dir, filename);
  fs.writeFileSync(outputPath, content, 'utf-8');

  return json({
    ok: true,
    company,
    employee: employeeRaw,
    employee_name: employeeName,
    filename,
    path: outputPath,
    folder: dir,
  });
});
