import { NextRequest } from 'next/server';
import { abort, json, route } from '@/lib/http';
import {
  commitUniqueMarkdown,
  getGitHubConfig,
  GitHubCommitError,
  GitHubConfigError,
  localStamp,
  slugifyName,
} from '@/lib/github';
import { record_answered_qid } from '@/lib/helpers';

export const dynamic = 'force-dynamic';

// Repo-relative parent folder; each employee gets one "<name>_answers" subfolder.
const PRIORITY_QUESTIONS_REPO_DIR = 'Governance_Files/Priority_Questions';

export const POST = route(async (req: NextRequest) => {
  const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;
  const company = String(body.company || '').trim();
  const employee = String(body.employee || '').trim();
  const question = String(body.question || '').trim();
  const answer = String(body.answer || '').trim();
  const qid = String(body.qid || '').trim();
  const answeredBy = String(body.answered_by || '').trim() || employee || 'Unknown';

  if (!company) {
    abort(400, 'company required');
  }
  // Validation mirrors the client gating.
  if (!employee) {
    abort(400, 'Please select an employee.');
  }
  if (!answer) {
    abort(400, 'Please enter an answer.');
  }

  // Reuse the Task Tracker GitHub integration/credentials.
  let cfg;
  try {
    cfg = getGitHubConfig();
  } catch (err) {
    if (err instanceof GitHubConfigError) {
      console.error('[priority_questions] GitHub not configured:', err.message);
      abort(500, err.message);
    }
    throw err;
  }

  const stamp = localStamp();
  // One folder per employee, reused across answers (created automatically by the
  // GitHub Contents API when the first file is committed under it).
  const employeeFolder = `${slugifyName(employee)}_answers`;
  const dirPath = `${PRIORITY_QUESTIONS_REPO_DIR}/${employeeFolder}`;

  const content = [
    '# Priority Question Answer',
    '',
    'Question:',
    question || '(not provided)',
    '',
    'Answer:',
    answer,
    '',
    'Answered By:',
    answeredBy,
    '',
    'Answered Date:',
    stamp.dateDisplay,
    '',
    'Answered Time:',
    stamp.timeDisplay,
    '',
    'Created At:',
    stamp.createdAt,
    '',
    '---',
    '',
    'Generated by Governance Workbench',
    '',
  ].join('\n');

  const baseName = `${stamp.datePart}_${stamp.timePart}_priority-answer`;
  try {
    const saved = await commitUniqueMarkdown(
      cfg,
      dirPath,
      baseName,
      content,
      (filename) => `Priority Questions: answer${qid ? ` ${qid}` : ''} for ${employee} (${filename})`,
    );
    // Persist the answered state so this question is dropped from the active
    // list and does not reappear after a refresh. Best-effort.
    if (qid) {
      try {
        await record_answered_qid(company, qid);
      } catch (err) {
        console.error('[priority_questions] record_answered_qid failed:', err);
      }
    }
    return json({
      ok: true,
      company,
      qid,
      employee,
      folder: employeeFolder,
      filename: saved.filename,
      repo_path: saved.repoPath,
      branch: cfg.branch,
      commit: saved.data?.commit?.sha || null,
      html_url: saved.data?.content?.html_url || null,
    });
  } catch (err) {
    if (err instanceof GitHubCommitError) {
      abort(err.status === 409 ? 409 : 502, `Could not save answer to GitHub: ${err.message}`);
    }
    throw err;
  }
});
