import { NextRequest } from 'next/server';
import { abort, json, route } from '@/lib/http';
import {
  commitUniqueMarkdown,
  getGitHubConfig,
  GitHubCommitError,
  GitHubConfigError,
  localStamp,
} from '@/lib/github';
import { generate_priority_questions_from_task, pretty_member_name } from '@/lib/helpers';

export const dynamic = 'force-dynamic';

// Meeting Markdown notes are committed here (reusing the Task Tracker GitHub flow).
const MEETINGS_REPO_DIR = 'Governance_Files/Meetings';

// Title -> readable, filesystem-safe filename token (e.g. "Project Kickoff" ->
// "Project_Kickoff").
function sanitizeTitle(title: string): string {
  const clean = String(title || '')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  return clean || 'Meeting';
}

// Triggered after a meeting is uploaded. Commits a Meeting Markdown note to
// Governance_Files/Meetings/ and then runs the existing Task Tracker analysis to
// generate Priority Questions (0 or more) assigned to the meeting attendees.
// Best-effort — a missing/failed Claude or GitHub never breaks the prior upload.
export const POST = route(async (req: NextRequest) => {
  const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;
  const company = String(body.company || '').trim();
  const title = String(body.title || '').trim();
  const meetingDate = String(body.meeting_date || '').trim();
  const meetingTime = String(body.meeting_time || '').trim();
  const uploadedBy = String(body.uploaded_by || '').trim() || 'Unknown';
  const summary = String(body.summary || '').trim();
  const claudeSummary = String(body.claude_summary || '').trim();
  const transcript = String(body.transcript || '').trim();
  const uploadedFile = String(body.uploaded_file || '').trim();
  const additionalDetails = String(body.additional_details || '').trim();
  const attendees = (Array.isArray(body.attendees) ? body.attendees : []) as Array<Record<string, unknown>>;

  if (!company) abort(400, 'company required');
  if (!title) abort(400, 'meeting title required');

  // Attendee display names + the team-member keys the questions get assigned to.
  const attendeeNames: string[] = [];
  const memberKeys: string[] = [];
  for (const a of attendees) {
    const memberKey = String(a['team_member_key'] || '').trim();
    const externalName = String(a['external_name'] || '').trim();
    if (memberKey) {
      attendeeNames.push(pretty_member_name(memberKey));
      memberKeys.push(memberKey);
    } else if (externalName) {
      attendeeNames.push(externalName);
    }
  }

  // Reuse the Task Tracker GitHub integration/credentials.
  let cfg;
  try {
    cfg = getGitHubConfig();
  } catch (err) {
    if (err instanceof GitHubConfigError) {
      console.error('[meetings] GitHub not configured:', err.message);
      abort(500, err.message);
    }
    throw err;
  }

  const stamp = localStamp();
  const content = [
    '# Meeting',
    '',
    'Title:',
    title,
    '',
    'Meeting Date:',
    meetingDate || stamp.datePart,
    '',
    'Team Attendees:',
    attendeeNames.length ? attendeeNames.join(', ') : '(none)',
    '',
    'Uploaded By:',
    uploadedBy,
    '',
    'Created Date:',
    stamp.dateDisplay,
    '',
    'Created Time:',
    stamp.timeDisplay,
    '',
    'Created At:',
    stamp.createdAt,
    '',
    'Claude Generated Summary:',
    claudeSummary || '(not generated)',
    '',
    'Original User Summary:',
    summary, // the user's own note — preserved separately, blank when not provided
    '',
    'Uploaded File:',
    uploadedFile || '(none)',
    '',
    'Additional Notes:',
    additionalDetails || '(none)',
    '',
    '---',
    '',
    'Generated by Governance Workbench',
    '',
  ].join('\n');

  const baseName = `${meetingDate || stamp.datePart}_${sanitizeTitle(title)}`;
  let filename = '';
  let repoPath = '';
  try {
    const saved = await commitUniqueMarkdown(
      cfg,
      MEETINGS_REPO_DIR,
      baseName,
      content,
      (name) => `Meetings: add ${title} (${name})`,
    );
    filename = saved.filename;
    repoPath = saved.repoPath;
  } catch (err) {
    if (err instanceof GitHubCommitError) {
      abort(err.status === 409 ? 409 : 502, `Could not save meeting to GitHub: ${err.message}`);
    }
    throw err;
  }

  // Build the analysis text — the full transcript comes first so Claude can
  // determine per-question ownership from the actual conversation (who was
  // assigned / committed to which work), not just from the attendee list.
  const analysisText = [
    `Meeting: ${title}`,
    meetingDate ? `Date: ${meetingDate}${meetingTime ? ` ${meetingTime}` : ''}` : '',
    attendeeNames.length ? `Attendees: ${attendeeNames.join(', ')}` : '',
    transcript ? `Meeting transcript (who said what, action items, owners, decisions, risks, follow-ups):\n"""\n${transcript}\n"""` : '',
    claudeSummary ? `Meeting summary: ${claudeSummary}` : '',
    summary ? `User note: ${summary}` : '',
    additionalDetails ? `Additional notes: ${additionalDetails}` : '',
  ].filter(Boolean).join('\n');

  let generation: any = { ok: true, count: 0, question_count: 0, created: [] };
  if (memberKeys.length) {
    generation = await generate_priority_questions_from_task(company, memberKeys, analysisText);
  }

  return json({
    ok: true,
    company,
    filename,
    repo_path: repoPath,
    branch: cfg.branch,
    attendees: attendeeNames,
    member_keys: memberKeys,
    question_count: generation.question_count ?? 0,
    created: generation.created ?? [],
    generation_skipped: Boolean(generation.skipped),
    generation_reason: generation.reason || null,
  });
});
